### ISSUE TITLE
Eventually helpful suggestions

### ISSUE THREAD

**Issue by dunahan** [WilliamDraco/nwsync_gui#1]
Using this GUI for the first time, two things I would mention. So they could help some users in the future. 

First one, the message window when you hit help cuts off at Group-ID. I'll post a screenshot, as soon it will be possible. 

Second one, if a error occurs (even with verbose output enabled), the GUI wouldn't tell you about. At my first try I didn't realized, that the GUI stopped.

So my suggestions are
1) resizing the help message window to a proper size, or make it resizable. Don't know what's possible with nim and GUIs. 
2) send a message window, like "A error occurred, a log was created. Take a look at it."

Thank you for this GUI that helps first timers at setting up a nwsync folder!

Dunahan

**Comment by WilliamDraco** [comment]
Interesting to hear about the help message being incorrectly sized. I'm actually not explicitly sizing it at all so it should just "fit to text"... I need to change that when I include Prune/Print (relatively soon) anyway, so I'll look to another way to do that - thanks.

As to the error messages, I'll consider what I could do with that. It only generates a log if the checkbox to do so is enabled, but I should be able to determine if there was an error, and tell the user about it at least for their knowledge... Do you know the wording of the error that you received?

**Comment by dunahan** [comment]
This error I received was about a file that wasn't supported. This file was in an older hak and it was only one among many.. In the log file (used write logs to dest and verbose output) I found that file and could remove it from the hak.

As said earlier, here is a link to the screen of the help window.
https://www.schwerterkueste.de/msgwin.png
At the bottom is the task bar of win 10. My resolution is 1600x900...

**Comment by WilliamDraco** [comment]
The help-menu portion of this is resolved in V1.0.0 main release by overhauling the help menu entirely.

With regards to alerting on-error, I'd need a bit more info on the exact nature of errors to be caught (exactly wording, mostly). NWSync doesn't output a special "Error" channel or text that I can spot -so not exactly sure what to look for and catch. If you can provide a specific (copy/paste) error text from the logs please open a new issue with it and I'll see about catching it :)
